theme: jekyll-theme-cayman
name: Diarmuid McDonnell
title: The impact of Covid-19 on the charity sector
subtitle: A cross-national comparison
description: Analyses of the impact of Covid-19 on charity sectors worldwide