theme: jekyll-theme-cayman
name: Diarmuid McDonnell
title: The impact of Covid-19 on the charity sector
description: A cross-national comparison
url: https://diarmuidm.github.io/charity-covid19
header_pages:
  - index.md
  - data.md
  - methodology.md
  - blog.html
  - contact.md